msrv = "1.55.0"
allow-expect-in-tests = true
allow-exact-repetitions = false
check-private-items = true
#disallowed-methods = [
#    "std::result::Result::unwrap",
#    "std::result::Result::expect",
#    "std::option::Option::unwrap",
#    "std::option::Option::expect",
#]
