name: Rust

on:
  pull_request:
    branches: [ "dev", "dev-next" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  RustTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: ./ci.sh
    - name: Test
      run: cargo test
