name: Rust

on:
  pull_request:
    branches: [ "master", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  RustTests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build
    - name: Format
      run: cargo fmt --check
    - name: Lint
      run: cargo clippy --all-features --all-targets
    - name: Test
      run: cargo test
  SemVerCheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check semantic versioning
      uses: obi1kenobi/cargo-semver-checks-action@v2
